load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

# Storage class, consumed by Tensor and TensorSlice
cc_library(
    name = "storage",
    hdrs = glob(
        [
            "src/include/Storage.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = []
)

# AbstractTensor class, implemented by Tensor and TensorSlice
cc_library(
    name = "abstracttensor",
    hdrs = glob(
        [
            "src/include/AbstractTensor.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":storage",
    ]
)

# Dimension Info struct used by Tensor and TensorSlice
cc_library(
    name = "diminfo",
    hdrs = glob(
        [
            "src/include/DimInfo.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = []
)

# Logging library present across nearly all of the individual libraries packages
cc_library(
    name = "llmlog",
    srcs = glob(
        [
            "src/Log.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/Log.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
)

# Numeric definitions for use by Tensor and TensorSlice, defining
# which types can be used and their associated double-width types
cc_library(
    name = "numerics",
    hdrs = glob(
        [
            "src/include/Numerics.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = []
)

# Math operations executed by Tensors and TensorSlices, checking for
# overflow and underflow, ensuring the right casting is used, etc.
cc_library(
    name = "tensormath",
    hdrs = glob(
        [
            "src/include/TensorMath.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":numerics",
    ]
)

# Tensor template library
cc_library(
    name = "tensor",
    hdrs = glob(
        [
            "src/include/Tensor.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":abstracttensor",
        ":llmlog",
        ":numerics",
        ":storage",
        ":tensormath",
    ]
)

# Tensor matmul kernel library
cc_library(
    name = "tensormatmul",
    hdrs = glob(
        [
            "src/include/TensorMatmul.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":abstracttensor",
        ":tensor",
        ":tensormath",
    ]
)

# TensorSlice template library
cc_library(
    name = "tensorslice",
    hdrs = glob(
        [
            "src/include/TensorSlice.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":abstracttensor",
        ":diminfo",
        ":llmlog",
        ":numerics",
        ":sliceconfig",
        ":storage",
        ":tensor",
    ]
)

# SliceConfig library, used for creating TensorSlices
cc_library(
    name = "sliceconfig",
    srcs = glob(
        [
            "src/SliceConfig.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/SliceConfig.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = []
)

# Abstract base class for any Tokenizer implementation
cc_library(
    name = "tokenizer",
    hdrs = glob(
        [
            "src/include/Tokenizer.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = []
)

# Byte Pair Encoding + BPE Tokenizer
cc_library(
    name = "bpe",
    srcs = glob(
        [
            "src/BytePairEncoding.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/BytePairEncoding.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":llmlog",
        ":tokenizer"
    ]
)

# Data loader
cc_library(
    name = "dataloader",
    srcs = glob(
        [
            "src/DataLoader.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/DataLoader.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":llmlog",
        ":tensor",
        ":tokenizer"
    ]
)

# Attention module
cc_library(
    name = "attention",
    srcs = glob(
        [
            "src/Attention.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/Attention.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":llmlog",
        ":tensor",
        ":tensormatmul",
        ":tensorslice"
    ]
)

cc_binary(
    name = "build-llm-cpp",
    srcs = glob(
        [
            "src/main.cpp"
        ]
    ),
    includes = [],
    deps = [
        ":attention",
        ":bpe",
        ":dataloader",
        ":llmlog",
        ":tensor",
        ":tensormatmul",
        ":tensorslice",
    ]
)

cc_test(
    name = "tensor_test",
    size = "small",
    srcs = ["tests/Tensor_Test.cpp"],
    copts = ["-Isrc/include"],
    deps = [
        ":tensor",
        "@googletest//:gtest_main",
    ],
    tags = ["no-clang-tidy"],
)

cc_test(
    name = "tensormatmul_test",
    size = "small",
    srcs = ["tests/TensorMatmul_Test.cpp"],
    copts = ["-Isrc/include"],
    deps = [
        ":tensor",
        ":tensormatmul",
        ":tensorslice",
        "@googletest//:gtest_main",
    ],
    tags = ["no-clang-tidy"],
)

cc_test(
    name = "tensorslice_test",
    size = "small",
    srcs = ["tests/TensorSlice_Test.cpp"],
    copts = ["-Isrc/include"],
    deps = [
        ":sliceconfig",
        ":tensor",
        ":tensorslice",
        "@googletest//:gtest_main",
    ],
    tags = ["no-clang-tidy"],
)

cc_test(
    name = "attention_test",
    size = "small",
    srcs = ["tests/Attention_Test.cpp"],
    copts = ["-Isrc/include"],
    deps = [
        ":attention",
        ":tensor",
        ":tensormatmul",
        ":tensorslice",
        "@googletest//:gtest_main",
    ],
    tags = ["no-clang-tidy"],
)