load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

# Logging library present across nearly all of the individual libraries packages
cc_library(
    name = "llmlog",
    srcs = glob(
        [
            "src/Log.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/Log.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
)

# Tensor template library
cc_library(
    name = "tensor",
    hdrs = glob(
        [
            "src/include/Tensor.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":llmlog",
    ]
)

# Abstract base class for any Tokenizer implementation
cc_library(
    name = "tokenizer",
    hdrs = glob(
        [
            "src/include/Tokenizer.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = []
)

# Byte Pair Encoding + BPE Tokenizer
cc_library(
    name = "bpe",
    srcs = glob(
        [
            "src/BytePairEncoding.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/BytePairEncoding.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":llmlog",
        ":tokenizer"
    ]
)

# Data loader
cc_library(
    name = "dataloader",
    srcs = glob(
        [
            "src/DataLoader.cpp"
        ]
    ),
    hdrs = glob(
        [
            "src/include/DataLoader.hpp"
        ]
    ),
    strip_include_prefix = "src",
    includes = [],
    deps = [
        ":llmlog",
        ":tensor",
        ":tokenizer"
    ]
)

cc_binary(
    name = "build-llm-cpp",
    srcs = glob(
        [
            "src/main.cpp"
        ]
    ),
    includes = [],
    deps = [
        ":llmlog",
        ":bpe",
        ":tensor",
        ":dataloader"
    ]
)
